# Generated by Django 3.1.7 on 2021-04-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.AlterField(
            model_name='validation',
            name='phonenumber',
            field=models.IntegerField(max_length=10),
        ),
    ]
