# Generated by Django 3.1.7 on 2021-04-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20210420_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
    ]
