# Generated by Django 3.1.7 on 2021-04-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20210421_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='phonenumber',
            field=models.IntegerField(max_length=15),
        ),
    ]
