# Generated by Django 3.1.7 on 2021-04-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20210421_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
